export const addUserApi = "https://mern-assigment-degrowfa-backend.vercel.app/adduser"
export const getUserApi = "https://mern-assigment-degrowfa-backend.vercel.app/getusers"
export const delteUserApi = "https://mern-assigment-degrowfa-backend.vercel.app/deleteuser"
export const updateUserApi = "https://mern-assigment-degrowfa-backend.vercel.app/updateuser"
export const downloadCsvTemplate = "https://mern-assigment-degrowfa-backend.vercel.app/downloadtemplatecsv"